name: Build & sign JAR (Java 21)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Create provenance JSON
        run: ART=target/demo-oidc-java-1.0.0.jar && SHA=$(sha256sum "$ART" | awk '{print $1}') && echo "{\"artifact\":\"$ART\",\"artifact_sha256\":\"$SHA\",\"repo\":\"https://github.com/${{ github.repository }}\",\"commit\":\"${{ github.sha }}\",\"workflow\":\"${{ github.workflow }}\",\"run_id\":\"${{ github.run_id }}\",\"runner_os\":\"${{ runner.os }}\"}" > provenance.json

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0
        with:
          cosign-release: "v3.0.2"

      - name: Sign JAR artifact
        run: cosign sign-blob --tlog-upload=true --yes --output-signature target/demo-oidc-java-1.0.0.jar.sig --output-certificate target/demo-oidc-java-1.0.0.jar.pem --bundle target/demo-oidc-java-1.0.0.jar.bundle target/demo-oidc-java-1.0.0.jar

      - name: Sign provenance JSON
        run: cosign sign-blob --tlog-upload=true --yes --output-signature provenance.json.sig --output-certificate provenance.json.pem --bundle provenance.json.bundle provenance.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/demo-oidc-java-1.0.0.jar
            target/demo-oidc-java-1.0.0.jar.sig
            provenance.json
            provenance.json.sig
